/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;
import com.formdev.flatlaf.intellijthemes.FlatSolarizedLightIJTheme;
import java.awt.Frame;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.SecureRandom;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static UI.dashboard.meow;
import static UI.dashboard.username;
/**
 *
 * @author Administrator
 */

public class  EditUsername extends javax.swing.JDialog {
public static String mydb_url = "jdbc:mysql://localhost:3306/eventsystem_db";
    public static String myDB_username = "root";  // Database username
    public static  String myDB_PASSWORD = "";  // Define your database password here
   private String currentUsername;
   public static String username_table;
     public static String captchaValue;
   
    private static final String CHARACTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    /**
     * Creates new form NewJDialog
     */
    public EditUsername(Frame parent, boolean modal, String username_table) {
        super(parent, modal);
        this.username_table = username_table; 
        initComponents();
        setLocationRelativeTo(null);
            setResizable(false);
            setTitle("Edit Username");

                 captchaValue = captcha_Generator(8);
                 captcha.setText(captchaValue);
     
    }
    
   public static String captcha_Generator(int length) {
    SecureRandom random = new SecureRandom();
    StringBuilder captcha = new StringBuilder();

    for (int i = 0; i < length; i++) {
        int index = random.nextInt(CHARACTERS.length());
        captcha.append(CHARACTERS.charAt(index));
    }

    return captcha.toString();
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        captcha = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        changeuser = new javax.swing.JButton();
        captchaenter = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        clear = new javax.swing.JButton();
        label6 = new java.awt.Label();
        Oldname = new javax.swing.JTextField();
        label5 = new java.awt.Label();
        Newname = new javax.swing.JTextField();
        label7 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(575, 658));
        jPanel2.setPreferredSize(new java.awt.Dimension(575, 658));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 110, 90));
        try {
            BufferedImage originalImage = ImageIO.read(getClass().getResource("/pictures/pwclogo.jpg"));
            BufferedImage resizedImage = resizeImage(originalImage,72, 72);  // Adjust the dimensions as needed

            ImageIcon imageIcon = new ImageIcon(resizedImage);
            jLabel5.setIcon(imageIcon);
        } catch (IOException e) {
            e.printStackTrace();
        }

        captcha.setText(captchaValue);
        captcha.setEditable(false);
        captcha.setBackground(new java.awt.Color(51, 51, 51));
        captcha.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        captcha.setForeground(new java.awt.Color(255, 255, 255));
        captcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captchaActionPerformed(evt);
            }
        });
        jPanel2.add(captcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 450, 40));

        label3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(128, 0, 0));
        label3.setText("Your current username");
        jPanel2.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 290, 30));

        changeuser.setBackground(new java.awt.Color(0, 153, 0));
        changeuser.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        changeuser.setForeground(new java.awt.Color(255, 255, 255));
        changeuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8-conference-foreground-selected-48.png"))); // NOI18N
        changeuser.setText("Change Username");
        changeuser.setToolTipText("");
        changeuser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        changeuser.setFocusTraversalPolicyProvider(true);
        changeuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeuserActionPerformed(evt);
            }
        });
        jPanel2.add(changeuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 230, 50));

        captchaenter.setBackground(new java.awt.Color(51, 51, 51));
        captchaenter.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        captchaenter.setForeground(new java.awt.Color(255, 255, 255));
        captchaenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captchaenterActionPerformed(evt);
            }
        });
        jPanel2.add(captchaenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 450, 40));

        label4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(128, 0, 0));
        label4.setText("Captcha");
        jPanel2.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 290, 30));

        clear.setBackground(new java.awt.Color(153, 0, 0));
        clear.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Close");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 231, 50));

        label6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label6.setForeground(new java.awt.Color(128, 0, 0));
        label6.setText("Edit Username");
        jPanel2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 250, 30));

        Oldname.setText(username_table);
        Oldname.setEditable(false);
        Oldname.setBackground(new java.awt.Color(51, 51, 51));
        Oldname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Oldname.setForeground(new java.awt.Color(255, 255, 255));
        Oldname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OldnameActionPerformed(evt);
            }
        });
        jPanel2.add(Oldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 450, 40));

        label5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(128, 0, 0));
        label5.setText("Type the captcha");
        jPanel2.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 290, 30));

        Newname.setBackground(new java.awt.Color(51, 51, 51));
        Newname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Newname.setForeground(new java.awt.Color(255, 255, 255));
        Newname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewnameActionPerformed(evt);
            }
        });
        jPanel2.add(Newname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 450, 40));

        label7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label7.setForeground(new java.awt.Color(128, 0, 0));
        label7.setText("New username");
        jPanel2.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void captchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_captchaActionPerformed

    private void changeuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeuserActionPerformed
                currentUsername = Oldname.getText();
        String newUsername = Newname.getText();
        String captchatype =captchaenter.getText();
         if (captchatype.equals(captchaValue)) {
            System.out.println("CAPTCHA matched. Proceed.");
        
        if (currentUsername.isEmpty() || newUsername.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please don't leave a single field empty", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                // Check if the new username already exists in the database
                if (doesUsernameExist(newUsername)) {
                    JOptionPane.showMessageDialog(null, "Username already exists", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    // Update the current username in the database
                    if (updateUsername(currentUsername, newUsername)) {
                        JOptionPane.showMessageDialog(null, "Username successfully changed", "", JOptionPane.INFORMATION_MESSAGE);
                              meow.dispose();
                            meow =  new dashboard(username);
                meow.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to change the username", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (SQLException | ClassNotFoundException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "An error occurred while checking the username.");
            }
       
        }
           } 
         else {
              System.out.println("CAPTCHA did not match. Regenerating a new CAPTCHA.");
            captchaValue = captcha_Generator(8);
            System.out.println("Generated CAPTCHA: " + captchaValue);
            captcha.setText( captchaValue);
                
                }
    

    
    }//GEN-LAST:event_changeuserActionPerformed

    private void captchaenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captchaenterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_captchaenterActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
     dispose();
        

    }//GEN-LAST:event_clearActionPerformed

    private void OldnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OldnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OldnameActionPerformed

    private void NewnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger( EditUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger( EditUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger( EditUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger( EditUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
           try {
	    	FlatSolarizedLightIJTheme.setup();
	    } catch (Exception e) {
	    	
	        e.printStackTrace();
	    }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 Image iconImage = Toolkit.getDefaultToolkit().getImage("src/pictures/sports.png");
                 EditUsername dialog = new  EditUsername(new javax.swing.JFrame(), true, username_table);
                   dialog.setIconImage(iconImage);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Newname;
    private javax.swing.JTextField Oldname;
    public static javax.swing.JTextField captcha;
    private javax.swing.JTextField captchaenter;
    private javax.swing.JButton changeuser;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    // End of variables declaration//GEN-END:variables

     private BufferedImage resizeImage(BufferedImage originalImage, int newWidth, int newHeight) {
    BufferedImage resizedImage = new BufferedImage(newWidth, newHeight, originalImage.getType());
    Graphics2D g = resizedImage.createGraphics();
    g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
    g.drawImage(originalImage, 0, 0, newWidth, newHeight, null);
    g.dispose();
    return resizedImage;
}
       void showDialog() {
        
        setVisible(true);
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
       
       // this is where to change the username
  private boolean updateUsername(String currentUsername, String newUsername) {
        try {
            Connection connection = DriverManager.getConnection(mydb_url, myDB_username, myDB_PASSWORD);
            Statement statement = connection.createStatement();

            // Check if the current username exists
            ResultSet resultSet = statement.executeQuery("SELECT * FROM user WHERE username = '" + currentUsername + "'");

            if (!resultSet.next()) {
                // The current username does not exist
                JOptionPane.showMessageDialog(null, "Current username does not exist", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }

            // Close the previous ResultSet before executing another query
            resultSet.close();

            // Check if the new username already exists
            resultSet = statement.executeQuery("SELECT * FROM user WHERE username = '" + newUsername + "'");

            if (resultSet.next()) {
                // The new username already exists
                JOptionPane.showMessageDialog(null, "Username already exists", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }

            // Update the current username in the database
            statement.executeUpdate("UPDATE user SET username = '" + newUsername + "' WHERE username = '" + currentUsername + "'");
            return true;
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "An error occurred while updating the username.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
  
// to check if user exist
   public boolean doesUsernameExist(String username) throws SQLException, ClassNotFoundException {
	    Class.forName("com.mysql.cj.jdbc.Driver");
            

	    try (Connection connection = DriverManager.getConnection(mydb_url,  myDB_username, myDB_PASSWORD)) {
	        String selectSQL = "SELECT COUNT(*) FROM user WHERE username = ?";
	        try (PreparedStatement selectStatement = connection.prepareStatement(selectSQL)) {
	            selectStatement.setString(1, username);

	            try (ResultSet resultSet = selectStatement.executeQuery()) {
	                if (resultSet.next()) {
	                    int count = resultSet.getInt(1);
	                    return count > 0;
	                }
	            }
	        }
	    }
	    return false;
	}


}
