/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;
import com.mysql.cj.xdevapi.Statement;
import com.sun.jdi.connect.spi.Connection;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.SQLException;
import javax.swing.UIManager;
import event_criteria_system.Login;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



import javax.swing.table.DefaultTableModel;
import static menu.registration_user.password;
import static menu.registration_user.username;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import java.sql.DriverManager;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
/**
 *
 * @author Administrator
 */
public class dashboard extends javax.swing.JFrame {
public static String confirmpassword;
private DefaultTableModel model;
    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
          // to set icons of your titlebar
           Image iconImage = Toolkit.getDefaultToolkit().getImage("pictures/sports.png");

        // Set the icon on the frame.
       setIconImage(iconImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Admin = new javax.swing.JButton();
        dash = new javax.swing.JButton();
        label2 = new java.awt.Label();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        evb = new javax.swing.JButton();
        label4 = new java.awt.Label();
        jButton5 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        dashboards = new javax.swing.JPanel();
        eventboard1 = new PanelRound();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        participants = new PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new PanelRound();
        label1 = new java.awt.Label();
        jPanel8 = new PanelRound();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel9 = new PanelRound();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new PanelRound();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new PanelRound();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new PanelRound();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        events = new javax.swing.JPanel();
        jPanel10 = new PanelRound();
        jPanel11 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        label5 = new java.awt.Label();
        searchingbar = new javax.swing.JTextField();
        addev = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        label6 = new java.awt.Label();
        jPanel12 = new PanelRound();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new PanelRound();
        jPanel16 = new javax.swing.JPanel();
        label7 = new java.awt.Label();
        User = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        confirmpass = new javax.swing.JPasswordField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Pass = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        clear = new javax.swing.JButton();
        adduser = new javax.swing.JButton();
        label8 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PWC Event Criteria System");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8-admin-48.png"))); // NOI18N
        Admin.setText("Admin");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        jPanel1.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 170, 67));

        dash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8-dashboard-48.png"))); // NOI18N
        dash.setText("Dashboard");
        dash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashActionPerformed(evt);
            }
        });
        jPanel1.add(dash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 170, 67));

        label2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("@Copyright  2023");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 960, 150, 40));

        jButton3.setText("logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8-user-60.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, 100));

        evb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/sports.png"))); // NOI18N
        evb.setText("Events");
        evb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evbActionPerformed(evt);
            }
        });
        jPanel1.add(evb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 170, 67));

        label4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("User:");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8-reports-58.png"))); // NOI18N
        jButton5.setText("Reports");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 170, 67));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 1000));

        dashboards.setBackground(new java.awt.Color(255, 255, 255));
        dashboards.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eventboard1.setBackground(new java.awt.Color(128, 0, 0));
        eventboard1.setForeground(new java.awt.Color(255, 255, 255));
        eventboard1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/sports.png"))); // NOI18N
        eventboard1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Events");
        eventboard1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 20));

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("0");
        eventboard1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 70, 20));

        dashboards.add(eventboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 320, 180));

        participants.setBackground(new java.awt.Color(128, 0, 0));
        participants.setForeground(new java.awt.Color(255, 255, 255));
        participants.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Participants");
        participants.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8-conference-foreground-selected-48.png"))); // NOI18N
        participants.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("0");
        participants.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 70, 20));

        dashboards.add(participants, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 320, 180));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        dashboards.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1090, 10));

        label1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label1.setText("Dashboard");
        dashboards.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 50));

        jPanel8.setBackground(new java.awt.Color(128, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Judges");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8-conference-foreground-selected-48.png"))); // NOI18N
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("0");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 70, 20));

        dashboards.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 320, 180));

        jPanel9.setBackground(new java.awt.Color(128, 0, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Reports");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8-reports-58.png"))); // NOI18N
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("0");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 70, 20));

        dashboards.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 320, 180));

        jPanel2.setBackground(new java.awt.Color(128, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Score Distributed");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 20));

        jPanel5.setBackground(new java.awt.Color(128, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Score Distributed");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 20));

        jPanel6.setBackground(new java.awt.Color(128, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Score Distributed");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 20));

        jPanel7.setBackground(new java.awt.Color(128, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Score Distributed");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 20));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 310, 180));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 310, 180));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 310, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8-score-48.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 50, 50));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("0");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 70, 20));

        dashboards.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 320, 180));

        label3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label3.setText("Welcome User");
        dashboards.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 460, 40));

        jTabbedPane1.addTab("tab1", dashboards);

        events.setBackground(new java.awt.Color(255, 255, 255));
        events.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        events.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1090, 10));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );

        events.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1070, 830));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8-trash-can-layout-for-a-indication-to-throw-trash-24.png"))); // NOI18N
        jButton1.setText("Delete a event");
        events.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 170, 40));

        jButton2.setBackground(new java.awt.Color(0, 153, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/search_954591 (1).png"))); // NOI18N
        jButton2.setText("Search");
        events.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 170, 40));

        label5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label5.setText("Events");
        events.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 50));
        events.add(searchingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 240, 40));

        addev.setBackground(new java.awt.Color(0, 153, 51));
        addev.setForeground(new java.awt.Color(255, 255, 255));
        addev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8-plus-32.png"))); // NOI18N
        addev.setText("Create a event");
        addev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addevActionPerformed(evt);
            }
        });
        events.add(addev, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 170, 40));

        jTabbedPane1.addTab("tab2", events);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label6.setText("Reports");
        jPanel4.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 50));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1090, 10));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1050, 860));

        jTabbedPane1.addTab("tab3", jPanel4);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(0, 0, 0));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1090, 10));

        jPanel16.setBackground(new java.awt.Color(128, 0, 0));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("Add User");
        jPanel16.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 190, 50));
        label7.getAccessibleContext().setAccessibleName("Admin");

        User.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        jPanel16.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, 50));
        User.getAccessibleContext().setAccessibleName("");

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Roles");
        jPanel16.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 20));

        jComboBox1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Judge" }));
        jPanel16.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 290, 40));

        confirmpass.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jPanel16.add(confirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 310, 50));

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Username");
        jPanel16.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Password");
        jPanel16.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 20));

        Pass.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jPanel16.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 310, 50));

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Confirmed password");
        jPanel16.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 20));

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Check to see the password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel16.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        clear.setBackground(new java.awt.Color(153, 0, 0));
        clear.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8-trash-can-layout-for-a-indication-to-throw-trash-24.png"))); // NOI18N
        clear.setText("Clear All");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel16.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 231, 78));

        adduser.setBackground(new java.awt.Color(0, 153, 51));
        adduser.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        adduser.setForeground(new java.awt.Color(255, 255, 255));
        adduser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icons8-plus-32.png"))); // NOI18N
        adduser.setText("Add User");
        adduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduserActionPerformed(evt);
            }
        });
        jPanel16.add(adduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 231, 78));

        jPanel14.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 360, 910));

        label8.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label8.setText("Admin");
        jPanel14.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 50));

        // Create a table model with button columns
        model = new DefaultTableModel() {
            public Class<?> getColumnClass(int column) {
                if (column == 4 || column == 5) { // Assuming delete is column 4 and edit is column 5
                    return JButton.class;
                } else {
                    return Object.class;
                }
            }
        };

        model.addColumn("ID");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Role");
        model.addColumn("Delete");
        model.addColumn("Edit");
        jTable1.setModel(model
        );
        jTable1.getColumn("Delete").setCellRenderer(new ButtonRenderer());
        jTable1.getColumn("Delete").setCellEditor(new ButtonEditor(new JCheckBox()));
        jTable1.getColumn("Edit").setCellRenderer(new ButtonRenderer());
        jTable1.getColumn("Edit").setCellEditor(new ButtonEditor(new JCheckBox()));

        // Create a custom editor for the column containing buttons
        jScrollPane1.setViewportView(jTable1);
        try {
            // Establish a database connection
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/eventsystem_db", "root", "");

            // Create a statement and execute a SELECT query
            java.sql.Statement statement = connection.createStatement();
            java.sql.ResultSet resultSet = statement.executeQuery("SELECT id, username, role, password from user");

            // Populate the DefaultTableModel with data from the ResultSet
            while (resultSet.next()) {
                int id = resultSet.getInt("id");
                String username = resultSet.getString("username");
                String role = resultSet.getString("password");
                String password = resultSet.getString("role");

                // Create buttons for delete and edit
                JButton deleteButton = new JButton("Delete");
                JButton editButton = new JButton("Edit");

                // Add action listeners to the buttons
                deleteButton.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                    }
                });

                editButton.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        // Handle edit button click
                        int selectedRow = jTable1.getSelectedRow();
                        // Implement your edit logic here using the selectedRow
                        // For example, you can retrieve the ID from the model
                        int idToEdit = (int) model.getValueAt(selectedRow, 0);
                        System.out.println("Edit button clicked for ID: " + idToEdit);
                    }
                });

                // Add data to the model, including buttons
                model.addRow(new Object[]{id, username, password, role, "Delete", "Edit"});
            }

            // Close the database connection
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        jPanel14.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 730, 910));

        jTabbedPane1.addTab("tab4", jPanel14);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -30, 1110, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  // Custom button renderer for JTable
   class ButtonRenderer extends JButton implements TableCellRenderer {
        public ButtonRenderer() {
            setOpaque(true);
        }

        public Component getTableCellRendererComponent(JTable jTable1, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            if (isSelected) {
                setForeground(jTable1.getSelectionForeground());
                setBackground(jTable1.getSelectionBackground());
            } else {
                setForeground(jTable1.getForeground());
                setBackground(UIManager.getColor("Button.background"));
            }
            setText((value == null) ? "" : value.toString());
            return this;
        }
    }

    // Custom button editor for JTable
    class ButtonEditor extends DefaultCellEditor {
        protected JButton button;
        private String label;
        private boolean isPushed;


        public ButtonEditor(JCheckBox checkBox) {
            super(checkBox);
            button = new JButton();
   
            button.setOpaque(true);
            button.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    fireEditingStopped();
                }
            });
        }

        public Component getTableCellEditorComponent(JTable jTable1, Object value, boolean isSelected, int row, int column) {
            if (isSelected) {
                button.setForeground(jTable1.getSelectionForeground());
                button.setBackground(jTable1.getSelectionBackground());
            } else {
                button.setForeground(jTable1.getForeground());
                button.setBackground(jTable1.getBackground());
            }
            label = (value == null) ? "" : value.toString();
            button.setText(label);
            isPushed = true;
            return button;
        }

        @Override
        public Object getCellEditorValue() {
             if (isPushed) {
            // Perform your action here based on the button click
            // In this example, we perform the database deletion
            if (label.equals("Delete")) {
                int row = jTable1.getSelectedRow();
                if (row >= 0) {
                    int idToDelete = (int) model.getValueAt(row, 0);
                    int confirmResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this user?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
                    if (confirmResult == JOptionPane.YES_OPTION) {
                        model.removeRow(row);
                        try {
                            String deleteQuery = "DELETE FROM user WHERE id = ?";
                            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/eventsystem_db", "root", "");
                            java.sql.PreparedStatement deleteStatement = connection.prepareStatement(deleteQuery);
                            deleteStatement.setInt(1, idToDelete);
                            int rowsDeleted = deleteStatement.executeUpdate();
                            if (rowsDeleted > 0) {
                                System.out.println("User with ID " + idToDelete + " deleted from the database.");
                            } else {
                                System.out.println("User deletion failed.");
                            }
                        } catch (SQLException ex) {
                            ex.printStackTrace();
                        }
                    }
                }
            }
        }
        isPushed = false;
        return label;
        }

        @Override
        public boolean stopCellEditing() {
            isPushed = false;
            return super.stopCellEditing();
        }

        @Override
        protected void fireEditingStopped() {
            super.fireEditingStopped();
        }
    }

   
     
    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(3);

    }//GEN-LAST:event_AdminActionPerformed

    private void dashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashActionPerformed
        // TODO add your handling code here:
               jTabbedPane1.setSelectedIndex(0);
     
    }//GEN-LAST:event_dashActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        int result = JOptionPane.showConfirmDialog(null, "Do you want to Logout?", "Confirmation", JOptionPane.YES_NO_OPTION);

if (result == JOptionPane.YES_OPTION) {
  // Delete the file.
    new Login().setVisible(true);
       dispose();
} else if (result == JOptionPane.NO_OPTION) {
  // Cancel the operation.
} else {
  // The user closed the dialog box without clicking on either button.
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void evbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evbActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(1);
           
    }//GEN-LAST:event_evbActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        // Check if the checkbox is selected.
        if (jCheckBox1.isSelected()) {
            // Set the JPasswordField to echo the password.
            confirmpass.setEchoChar((char) 0);
            Pass.setEchoChar((char) 0);
        } else {
            // Set the JPasswordField to not echo the password.
            confirmpass.setEchoChar('*');
            Pass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_clearActionPerformed

    private void adduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduserActionPerformed
        // TODO add your handling code here:
      
    username = User.getText();
    password = new String(Pass.getPassword());
    confirmpassword = new String(confirmpass.getPassword());
    if (username.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Username cannot be empty!", "Error", JOptionPane.ERROR_MESSAGE);
} else {
       if(password.isEmpty() || confirmpassword.isEmpty()){
             JOptionPane.showMessageDialog(null, "Empty Password!", "Error", JOptionPane.ERROR_MESSAGE);
       }
       else {
           if (!password.equals(confirmpassword)) {
        JOptionPane.showMessageDialog(null, "Passwords do not match!", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        if (verifyPasswordLength(confirmpassword)) {
            boolean hasCapsLock = false;
            boolean hasSpecialCharacters = false;

            for (char character : confirmpassword.toCharArray()) {
                if (Character.isUpperCase(character)) {
                    hasCapsLock = true;
                } else if (!Character.isLetterOrDigit(character)) {
                    hasSpecialCharacters = true;
                }
            }

            if (!hasCapsLock || !hasSpecialCharacters) {
                JOptionPane.showMessageDialog(null, "The password must contain at least one uppercase letter and one special character.");
            } else {
                try {
                    registration_user user = new registration_user();
                    user.create();
                } catch (NoSuchAlgorithmException | InvalidKeySpecException | ClassNotFoundException ex) {
                    Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
       }
    }
    
    }//GEN-LAST:event_adduserActionPerformed

    private void addevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addevActionPerformed
        // TODO add your handling code here:
          create_event dialog = new create_event(new java.awt.Frame(), true);
    dialog.showDialog();
     dialog.setTitle("Create Event");
         
    }//GEN-LAST:event_addevActionPerformed

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }
public static boolean verifyPasswordLength(String password) {
    int length = password.length();
    return length >= 8 && length <= 20;
} 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    public static javax.swing.JPasswordField Pass;
    public static javax.swing.JTextField User;
    private javax.swing.JButton addev;
    private javax.swing.JButton adduser;
    private javax.swing.JButton clear;
    public static javax.swing.JPasswordField confirmpass;
    private javax.swing.JButton dash;
    private javax.swing.JPanel dashboards;
    private javax.swing.JButton evb;
    public static transient volatile javax.swing.JPanel eventboard1;
    private javax.swing.JPanel events;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    public static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private javax.swing.JPanel participants;
    private javax.swing.JTextField searchingbar;
    // End of variables declaration//GEN-END:variables
}
