/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package menu;

import com.formdev.flatlaf.intellijthemes.FlatSolarizedLightIJTheme;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Administrator
 */
public class  EditUsername extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public EditUsername(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
            setResizable(false);
            setTitle("Edit Username");


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        Oldname = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        Newname = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        clear = new javax.swing.JButton();
        confirmpassword = new javax.swing.JPasswordField(20);
        password = new javax.swing.JPasswordField(20);
        label6 = new java.awt.Label();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(575, 658));
        jPanel2.setPreferredSize(new java.awt.Dimension(575, 658));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 110, 90));
        try {
            BufferedImage originalImage = ImageIO.read(getClass().getResource("/pictures/pwclogo.jpg"));
            BufferedImage resizedImage = resizeImage(originalImage,72, 72);  // Adjust the dimensions as needed

            ImageIcon imageIcon = new ImageIcon(resizedImage);
            jLabel5.setIcon(imageIcon);
        } catch (IOException e) {
            e.printStackTrace();
        }

        label2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(128, 0, 0));
        label2.setText("Confirmed password");
        jPanel2.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 290, 30));

        Oldname.setEditable(false);
        Oldname.setBackground(new java.awt.Color(51, 51, 51));
        Oldname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Oldname.setForeground(new java.awt.Color(255, 255, 255));
        Oldname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OldnameActionPerformed(evt);
            }
        });
        jPanel2.add(Oldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 450, 40));

        label3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(128, 0, 0));
        label3.setText("Your current username");
        jPanel2.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 290, 30));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8-conference-foreground-selected-48.png"))); // NOI18N
        jButton1.setText("Change Username");
        jButton1.setToolTipText("");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setFocusTraversalPolicyProvider(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 230, 50));

        Newname.setBackground(new java.awt.Color(51, 51, 51));
        Newname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Newname.setForeground(new java.awt.Color(255, 255, 255));
        Newname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewnameActionPerformed(evt);
            }
        });
        jPanel2.add(Newname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 450, 40));

        label4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(128, 0, 0));
        label4.setText("New username");
        jPanel2.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 290, 30));

        label5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(128, 0, 0));
        label5.setText("Password");
        jPanel2.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 290, 30));

        clear.setBackground(new java.awt.Color(153, 0, 0));
        clear.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8-trash-can-layout-for-a-indication-to-throw-trash-24.png"))); // NOI18N
        clear.setText("Clear All");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 231, 50));

        confirmpassword.setBackground(new java.awt.Color(51, 51, 51));
        confirmpassword.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        confirmpassword.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 450, 40));

        password.setBackground(new java.awt.Color(51, 51, 51));
        password.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 450, 40));

        label6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label6.setForeground(new java.awt.Color(128, 0, 0));
        label6.setText("Create a event");
        jPanel2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 250, 30));

        jCheckBox2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(128, 0, 0));
        jCheckBox2.setText("Check to see the password");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OldnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OldnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OldnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = Oldname.getText();
        String username1 = Newname.getText();
        String passwordj = new String(password.getPassword());
        String passwordj1 = new String(confirmpassword.getPassword());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NewnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewnameActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_clearActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:

        // TODO add your handling code here:
        // Check if the checkbox is selected.
        if (jCheckBox2.isSelected()) {
            // Set the JPasswordField to echo the password.
            password.setEchoChar((char) 0);
            confirmpassword.setEchoChar((char) 0);

        } else {
            // Set the JPasswordField to not echo the password.
            password.setEchoChar('\u2022'); // Use the bullet character as the echo character
            confirmpassword.setEchoChar('\u2022');

        }

    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger( EditUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger( EditUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger( EditUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger( EditUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
           try {
	    	FlatSolarizedLightIJTheme.setup();
	    } catch (Exception e) {
	    	
	        e.printStackTrace();
	    }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 Image iconImage = Toolkit.getDefaultToolkit().getImage("src/pictures/sports.png");
                 EditUsername dialog = new  EditUsername(new javax.swing.JFrame(), true);
                   dialog.setIconImage(iconImage);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Newname;
    private javax.swing.JTextField Oldname;
    private javax.swing.JButton clear;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables

     private BufferedImage resizeImage(BufferedImage originalImage, int newWidth, int newHeight) {
    BufferedImage resizedImage = new BufferedImage(newWidth, newHeight, originalImage.getType());
    Graphics2D g = resizedImage.createGraphics();
    g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
    g.drawImage(originalImage, 0, 0, newWidth, newHeight, null);
    g.dispose();
    return resizedImage;
}
       void showDialog() {
        
        setVisible(true);
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
